apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iyrr4y5bk-java-quarkus
  janus-idp.io/tekton: iyrr4y5bk-java-quarkus
  backstage.io/kubernetes-id: iyrr4y5bk-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iyrr4y5bk-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
